### ISSUE TITLE
nfc adapter not requested to power on

### ISSUE THREAD

**Issue by piggz** [mer-hybris/nfcd-binder-plugin#13]
On all of my ports NFC doesnt work on the current code in 4.5.0.19 ... On the FXTec Pro1 it did work at some point in the past as thats what I used to write some tags.

After a log of debugging and hacking, i believe that the nfcd daemon never requests the binder plugin to power on the adapter.  After hacking this into the code, i was able to read tags just fine. see https://github.com/piggz/nfcd/commit/f097db3270c7ca847865dae24521d046db920436 in the nfc manager code.

I then found an AlwaysOn setting which sets the adapter power on state in https://github.com/piggz/nfcd/blob/master/plugins/settings/settings_plugin.c#L968

This half fixes the issue ... now, when nfcd starts, it powers on the binder device ok, and tags can be read, however, if the nfc toggle is disabled/enabled then it stats in a powered-off state.

I may be missing something, as there is clearly a lot of code for handling the enabled and powered state, but i can seem to get it to work correctly.

This affects the Pro1, Pro1X and 4x Volla devices, all different SoCs and android versions.

**Comment by piggz** [comment]
Im retty sure adding a call to nfc_manager_request_powered here would fix it, but not sure if thats right (tm) https://github.com/sailfishos/nfcd/blob/master/plugins/settings/settings_plugin.c#L488

**Comment by piggz** [comment]
This does seem to fix things for me, but may not be correct https://github.com/sailfishos/nfcd/compare/master...piggz:nfcd:master

**Comment by monich** [comment]
The issue got resolved by installing [nfcd-mce-plugin](https://github.com/mer-hybris/nfcd-mce-plugin/), doesn't it?

**Comment by piggz** [comment]
correct
