### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by JamiKettunen** [mer-hybris/nfcd-binder-plugin#14]
As per https://github.com/mer-hybris/nfcd-binder-plugin/blob/4e92105/src/binder_nfc.h#L1-L31 the source code is licensed under a [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html), yet the repository root is missing a `LICENSE` file, which is required to be distributed along with installed binaries.

**Comment by monich** [comment]
Version 1.1.9 has the license (and even installs it if you're building an rpm)
